import type {Metadata} from 'next'
import './globals.scss'
import {Providers} from "@/app/providers";
import {Header} from "@/widgets/header";
import {Footer} from "@/widgets/footer";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Header/>
                    {children}
                    <Footer/>
                </Providers>
            </body>
        </html>
    )
}
